<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>
            <?php
            //site setting helper function
            $getSiteSetting =  getSiteSetting();
                if(isset($getSiteSetting)){
                    echo escape_output($getSiteSetting->site_title);
                }
            ?>  
        </title>
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <!-- Bootstrap 3.3.7 -->
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/bower_components/bootstrap/dist/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/bower_components/font-awesome/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/bower_components/Ionicons/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/dist/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. Choose a skin from the css/skins
             folder instead of downloading all of them to reduce the load. -->
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/dist/css/skins/_all-skins.min.css">
        <!-- Favicon -->
        <link rel="shortcut icon" href="<?php echo base_url(); ?>assets/images/favicon.ico" type="image/x-icon">
        <!-- Favicon -->
        <link rel="icon" href="<?php echo base_url(); ?>assets/images/favicon.ico" type="image/x-icon">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="<?php echo base_url(); ?>assets/plugins/local/html5shiv.min.js"></script>
        <script src="<?php echo base_url(); ?>assets/plugins/local/respond.min.js"></script>
        <![endif]-->

        <!-- Google Font -->
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/plugins/local/google_font.css">
        <link rel="stylesheet" href="<?php echo base_url(); ?>assets/css/forgot_password_success.css">
    </head>
    <!-- ADD THE CLASS sidebar-collapse TO HIDE THE SIDEBAR PRIOR TO LOADING THE SITE -->
    <body>
        <!--<body class="hold-transition skin-blue sidebar-collapse sidebar-mini">-->


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">  
            <!-- Main content -->
            <section class="content">
                <div class="login-logo border_ra" style="background-color: <?php echo escape_output($getSiteSetting->base_color); ?>; padding: 10px; box-shadow: 0 0 15px lightgreen;">
                    <a href="#">
                        <?php
                        if(isset($getSiteSetting) && $getSiteSetting->site_logo):
                            ?>
                            <img src="<?php echo base_url().'assets/images/'; ?><?php echo escape_output($getSiteSetting->site_logo); ?>">
                            <?php
                        else:
                            ?>
                            <img src="<?php echo base_url().'assets/branding/logo.png'; ?>">
                            <?php
                        endif;
                        ?>
                    </a>
                </div>
                <!-- Default box -->
                <div class="box"> 
                    <div class="box-footer">
                        <h4 class="box-title"><?php echo lang('AnautogeneratedpasswordhasbeensenttoyourEmail'); ?></h4>
                        <h4 class="box-title"><?php echo lang('PleasecheckyourEmail'); ?></h4>

                    </div>

                    <p class="padding_c"><a href="<?php echo base_url(); ?>Authentication/index">Go back to Login</a>
                        <br>
                        <br>
                </div>
                <!-- /.box -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <?php
            if(isset($getSiteSetting) && $getSiteSetting->footer):
                echo escape_output($getSiteSetting->footer);
            else:
                ?>
                Door Knock - <a href="http://doorsoft.xyz">ডোর সফট</a> কর্তৃক সর্বস্বত্ত্ব সংরক্ষিত
                <?php
            endif;
            ?>
        </footer> 
    </div>
    <!-- ./wrapper -->


</body>
</html>
